NewsletterApp/Models/Entities/NewsContent.cs
using NewsletterApp.Models.Common;

namespace NewsletterApp.Models.Entities;

public class NewsContent : AuditableEntity
{
    public string Title { get; set; }
    public string Content { get; set; }
    
    public Guid NewsLetterId { get; set; }
    public NewsLetter NewsLetter { get; set; }
}

NewsletterApp/Controllers/NewsContentController.cs
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsletterApp.Logic.Interfaces;
using NewsletterApp.Shared.Models.DTO;

namespace NewsletterApp.Controllers;

[Authorize]
public class NewsContentController : Controller
{
    private readonly INewsLetterContentsService _newsLetterContentsService;
    private readonly IHttpService _httpService;
    private readonly ILogger<NewsContentController> _logger;

    public NewsContentController(INewsLetterContentsService newsLetterContentsService,
        IHttpService httpService,
        ILogger<NewsContentController> logger)
    {
        _newsLetterContentsService = newsLetterContentsService;
        _httpService = httpService;
        _logger = logger;
    }
    
    public async Task<IActionResult> Index(Guid id)
    {
        var response = await _newsLetterContentsService.GetNewsLettersContentForNewsLetter(id);
        
        return View(response);
    }
    
    public async Task<IActionResult> CreateGetView(Guid newsLetterId)
    {
        ViewBag.NewsLetterId = newsLetterId;
        
        return View("Create");
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(CreateNewsLetterContentDto model)
    {
        var response = await _newsLetterContentsService.Create(model);
        
        if (response.StatusCode == 1)
        {
            return RedirectToAction("Index", new { id = model.NewsLetterId });
        }
        
        ViewBag.NewsLetterId = model.NewsLetterId;
        
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await _newsLetterContentsService.GetUpdateModel(id);
        
        return View(response);
    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(UpdateNewsLetterContentDto model)
    {
        var response = await _newsLetterContentsService.Update(model);
        
        if (response.StatusCode == 1)
        {
            return RedirectToAction("Index", new { id = model.NewsLetterId });
        }
        
        return View(model);
    }
    
    public async Task<IActionResult> Delete(Guid id, Guid newsLetterId)
    {
        var response = await _newsLetterContentsService.Delete(id);
        
        return RedirectToAction("Index", new { id = newsLetterId });
    }

    [HttpGet]
    public async Task<IActionResult> Send(Guid id, Guid newsLetterId)
    {
        var url = $"{Environment.GetEnvironmentVariable("MAIL_SENDER_URL")}/MailSender/SendMails?id={id}";

        try
        {
            var response = await _httpService.GetAsync(url);
        }
        catch (Exception e)
        {
            _logger.LogError(e.Message);
        }
        
        return RedirectToAction("Index", "NewsLetter", new { id = newsLetterId });
    }
}

NewsletterApp/Views/NewsContent/Create.cshtml
@model NewsletterApp.Shared.Models.DTO.CreateNewsLetterContentDto

@{
    Layout = "_Layout";
}

<form method="post" asp-controller="NewsContent" asp-action="Create">
    <input asp-for="NewsLetterId" value="@ViewBag.NewsLetterId" type="hidden"/>
    <div class="form-group mb-2">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control"/>
    </div>
    <div class="form-floating">
        <textarea class="form-control" asp-for="Content" placeholder="Leave a comment here" id="content" style="height: 100px"></textarea>
        <label for="content">Content</label>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

NewsletterApp/Views/NewsContent/Edit.cshtml
@model NewsletterApp.Shared.Models.DTO.UpdateNewsLetterContentDto

@{
    Layout = "_Layout";
}

<h2>Edit</h2>
<form method="post" asp-controller="NewsContent" asp-action="Edit">
    <input asp-for="Id" type="hidden"/>
    <input asp-for="NewsLetterId" type="hidden"/>
    <div class="form-group mb-2">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control"/>
    </div>
    <div class="form-floating mb-2">
        <textarea class="form-control" asp-for="Content" placeholder="Leave a comment here" id="content" style="height: 100px"></textarea>
        <label for="content">Content</label>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

NewsletterApp/Views/NewsContent/Index.cshtml
@model NewsletterApp.Shared.Models.ViewModels.NewsLetterContentVm

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>@Model.NewsLetterTitle</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            <a class="btn btn-success" href="@Url.Action("CreateGetView", "NewsContent", new { newsLetterId = Model.NewsLetterId })">Create news</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table table-striped text-center">
                <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Send</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.NewsLetterContentDtos)
                {
                    <tr>
                        <td>@item.Title</td>
                        <td>
                            <a id="sendButton" class="btn btn-success" href="https://localhost:13001/MailSender/SendMails/@item.Id">Send</a>
                        </td>
                        <td>
                            <a class="btn btn-warning" href="@Url.Action("Edit", "NewsContent", new { id = item.Id })">Edit</a>
                        </td>
                        <td>
                            <a class="btn btn-danger" href="@Url.Action("Delete", "NewsContent", new { id = item.Id, newsLetterId = Model.NewsLetterId })">Delete</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('#sendButton').click(function (e) {
            e.preventDefault();
            var url = $(this).attr('href');
            $.get(url, function (data) {
                console.log('Żądanie wysłane pomyślnie');
            });
        });
    });
</script>