NewsletterApp/Controllers/NewsLetterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsletterApp.Logic.Interfaces;
using NewsletterApp.Shared.Models.DTO;

namespace NewsletterApp.Controllers;

[Authorize]
public class NewsLetterController : Controller
{
    private readonly INewLettersService _newLettersService;

    public NewsLetterController(INewLettersService newLettersService)
    {
        _newLettersService = newLettersService;
    }
    
    public async Task<IActionResult> Index()
    {
        var model = await _newLettersService.GetList();
        
        return View(model);
    }
    
    [HttpGet]
    [AllowAnonymous]
    public async Task<IActionResult> Subscribe(Guid id)
    {
        ViewBag.NewsLetterId = id;
        
        return View();
    }
    
    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Subscribe(SubscribeNewsLetterDto dto)
    {
        var result = await _newLettersService.Subscribe(dto.NewsLetterId, dto.Email);
        
        return RedirectToAction("Index", "Home");
    }
    
    [AllowAnonymous]
    public async Task<IActionResult> Unsubscribe(Guid subscriberId, Guid newsLetterId)
    {
        var result = await _newLettersService.Unsubscribe(newsLetterId, subscriberId);
        
        ViewBag.Message = result.Message;
        return View("UnsubscribeInfo");
    }
    
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(CreateNewsLetterDto model)
    {
        var result = await _newLettersService.Create(model);
        
        if (result.StatusCode == 1)
        {
            return RedirectToAction("Index");
        }

        return View(model);
    }
    
    public async Task<IActionResult> Delete(Guid id)
    {
        var result = await _newLettersService.Delete(id);
        
        return RedirectToAction("Index");
    }
    
    public async Task<IActionResult> Edit(Guid id)
    {
        var result = await _newLettersService.GetEditDto(id);
        
        if (result == null)
        {
            return RedirectToAction("Index");
        }
        
        return View(result);
    }
    
    public async Task<IActionResult> SaveEdit(EditNewsLetterDto dto)
    {
        var result = await _newLettersService.SaveEditedNewsLetter(dto);
        
        if (result.StatusCode == 1)
        {
            return RedirectToAction("Index");
        }
        
        return RedirectToAction("Edit", dto);
    }
}

NewsletterApp/Controllers/UserAuthenticationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsletterApp.Logic.Interfaces;
using NewsletterApp.Shared.Models.DTO;

namespace NewsletterApp.Controllers;

public class UserAuthenticationController : Controller
{
    private readonly IUserAuthenticationService _authService;

    public UserAuthenticationController(IUserAuthenticationService authService)
    {
        _authService = authService;
    }

    [AllowAnonymous]
    public async Task<IActionResult> RegisterAdmin()
    {
        RegistrationModel model = new RegistrationModel
        {
            Username = "admin",
            Email = "admin@gmail.com",
            FirstName = "Adam",
            LastName = "Ludwiczak",
            Password = "Pass123$"
        };
        model.Role = "admin";
        var result = await _authService.RegisterAsync(model);
        return RedirectToAction("Login");
    }

    public IActionResult Login()
    {
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Login(LoginModel model)
    {
        if (!ModelState.IsValid)
            return View(model);
        var result = await _authService.LoginAsync(model);
        if (result.StatusCode == 1)
        {
            return RedirectToAction("Index", "Home");
        }
        else
        {
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Login));
        }
    }

    public IActionResult Registration()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Registration(RegistrationModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        model.Role = "user";
        var result = await _authService.RegisterAsync(model);
        TempData["msg"] = result.Message;
        return RedirectToAction(nameof(Registration));
    }

    [Authorize]
    public async Task<IActionResult> Logout()
    {
        await _authService.LogoutAsync();
        return RedirectToAction(nameof(Login));
    }

    [Authorize]
    public IActionResult ChangePassword()
    {
        return View();
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
    {
        if (!ModelState.IsValid)
            return View(model);
        var result = await _authService.ChangePasswordAsync(model, User.Identity.Name);
        TempData["msg"] = result.Message;
        return RedirectToAction(nameof(ChangePassword));
    }
}

NewsletterApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - NewsletterApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/NewsletterApp.styles.css" asp-append-version="true"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NewsletterApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (string.IsNullOrEmpty(User.Identity.Name))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="#">Home</a>
                        </li>
                        <li class="nav-item" class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserAuthentication" asp-action="Login">Login</a>
                        </li>
                    }
                    @if (User.IsInRole("admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="NewsLetter" asp-action="Index">News Letters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserAuthentication" asp-action="Registration">Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserAuthentication" asp-action="ChangePassword">ChangePassword</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserAuthentication" asp-action="Logout">Logout</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>